version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:latest
    steps:
      - run:
          name: checkout
          command: |
            sudo apt-get -y update
            sudo apt-get -y upgrade

      - run:
          name: repository
          command: |
            sudo git clone https://github.com/Bralor/python_academy
            cd python_academy
            pip install -r requirements.txt

      - run:
          name: test
          command: |
            pytest tests -v

workflows:
  version: 2.1
  build_and_test:
      jobs:
      - build-and-test
